spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/session"
    username: postgres
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    #hibernate:
     # ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: "1_001"
    ignore-future-migrations: false






